import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import { config } from "../../config.js";
import { supabase } from "../../lib/supabase.js";

export class WebsiteFactoryAdapter {
  private templateVault: string;
  private outputBaseDir: string;

  constructor() {
    const rootDesktop = path.join(process.env.USERPROFILE || process.env.HOME || "", "Desktop", "Antigravity");
    
    // Resolve configurable paths with fallbacks to avoid hardcoding
    this.templateVault = config.templateVaultPath || path.join(rootDesktop, "Template Vault");
    this.outputBaseDir = config.generatedSitesPath || path.join(rootDesktop, "Generated Sites");
  }

  /**
   * Staps out a website mockup for a B2B client based on their niche.
   */
  async stampSite(clientName: string, niche = "base"): Promise<{ success: boolean; message: string; path?: string }> {
    try {
      const clientDirName = clientName.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      const outputDir = path.join(this.outputBaseDir, clientDirName);

      // Determine template source
      let sourceTemplate = path.join(this.templateVault, `${niche}-template`);
      
      // Fallback for roofer template in local tests
      if (niche === "roofer" && !fs.existsSync(sourceTemplate)) {
        const rootDesktop = path.join(process.env.USERPROFILE || process.env.HOME || "", "Desktop", "Antigravity");
        sourceTemplate = path.join(rootDesktop, "Roofers in Staffordshire", "roofer-site-template");
      }

      if (!fs.existsSync(sourceTemplate)) {
        return {
          success: false,
          message: `Template for niche '${niche}' not found at path: ${sourceTemplate}`
        };
      }

      if (fs.existsSync(outputDir)) {
        return {
          success: false,
          message: `A mockup site for client "${clientName}" already exists at: ${outputDir}`
        };
      }

      // Ensure target base directory exists
      fs.mkdirSync(this.outputBaseDir, { recursive: true });

      // 1. Clone Template
      console.log(`[Website Factory] Copying template from ${sourceTemplate} to ${outputDir}`);
      fs.cpSync(sourceTemplate, outputDir, { recursive: true });

      // 2. Remove old git history
      const oldGit = path.join(outputDir, ".git");
      if (fs.existsSync(oldGit)) {
        fs.rmSync(oldGit, { recursive: true, force: true });
      }

      // 3. Customize index.html
      const indexHtmlPath = path.join(outputDir, "index.html");
      if (fs.existsSync(indexHtmlPath)) {
        let html = fs.readFileSync(indexHtmlPath, "utf-8");
        html = html.replace(/<title>.*?<\/title>/, `<title>${clientName}</title>`);
        html = html.replace(/<meta name="description" content=".*?"/, `<meta name="description" content="Premium website built for ${clientName}"`);
        fs.writeFileSync(indexHtmlPath, html);
      }

      // 4. Customize package.json
      const pkgPath = path.join(outputDir, "package.json");
      if (fs.existsSync(pkgPath)) {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
        pkg.name = clientDirName;
        pkg.description = `Website for ${clientName}`;
        fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
      }

      // 5. Initialize fresh Git repo
      try {
        execSync("git init", { cwd: outputDir, stdio: "ignore" });
      } catch (e) {
        console.warn("[Website Factory] Git init failed during site generation.");
      }

      // 6. Update database record in Supabase projects table
      if (supabase) {
        try {
          await supabase.from("projects").insert({
            name: clientName,
            type: "client",
            status: "active",
            health: "good",
            last_update: "Mockup site template generated by Website Factory."
          });
          
          await supabase.from("activity_log").insert({
            type: "task",
            title: "Website Generated",
            description: `Generated ${niche} mockup site for ${clientName}`
          });
        } catch (dbErr: any) {
          console.error("[Website Factory] Failed to sync project row to Supabase:", dbErr.message);
        }
      }

      return {
        success: true,
        message: `Successfully generated ${niche} website for ${clientName}!`,
        path: outputDir
      };
    } catch (err: any) {
      return {
        success: false,
        message: `Stamping failed: ${err.message}`
      };
    }
  }
}

export const websiteFactory = new WebsiteFactoryAdapter();
