import { config } from "../../config.js";

/**
 * ── LinkedIn OS Placeholder Adapter ──
 * Operates in local/manual prompt mode until the LinkedIn Growth OS repository exists.
 */
export class LinkedInOSAdapter {
  private repositoryPath: string;

  constructor() {
    this.repositoryPath = config.linkedinOsPath || "";
  }

  /**
   * Generates a LinkedIn post based on user instructions and target topics.
   * Runs in manual prompt/generation mode when repository is not linked.
   */
  async generatePost(topic: string, guidelines?: string): Promise<string> {
    if (this.repositoryPath) {
      console.log(`[LinkedIn OS] Generating post via repo path: ${this.repositoryPath}`);
      // Placeholder for future repository imports/CLI executions
      return `Generated post for topic "${topic}" using repository rules at ${this.repositoryPath}`;
    }

    console.log("[LinkedIn OS] Running in manual prompt mode (local/fallback).");
    return `📝 **[LinkedIn Post Draft - Manual Mode]**\n\nTopic: ${topic}\n\nDraft content will be generated by the model based on this topic. Refine via chat.`;
  }

  /**
   * Conducts a profile audit or weekly growth review.
   */
  async generateWeeklyReview(metrics: Record<string, any>): Promise<string> {
    return `📊 **[LinkedIn Weekly Review]**\n- Impressions: ${metrics.impressions || 0}\n- Profile Views: ${metrics.views || 0}\n- Mode: Manual placeholder.`;
  }
}

export const linkedinOS = new LinkedInOSAdapter();
